services:
  - type: web
    name: webchat-backend
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://jipepe13.github.io/windsurf-project
